const products=[
{id:'1',name:'Obsidian Oversized Tee',cat:'men',price:1499,old:0,tag:'NEW',sizes:['S','M','L','XL'],colors:['Black','Charcoal'],desc:'Heavyweight cotton with a relaxed oversized cut.',new:1,sale:0},
{id:'2',name:'Raven Utility Jacket',cat:'men',price:4999,old:5999,tag:'SALE',sizes:['S','M','L','XL'],colors:['Black'],desc:'Structured utility jacket with functional pocket detailing.',new:0,sale:1},
{id:'3',name:'Noir Cargo Trouser',cat:'men',price:3299,old:0,tag:'NEW',sizes:['28','30','32','34','36'],colors:['Black','Stone'],desc:'Tapered cargo trousers with a clean modern finish.',new:1,sale:0},
{id:'4',name:'Ravan Signature Hoodie',cat:'unisex',price:2899,old:0,tag:'BESTSELLER',sizes:['S','M','L','XL'],colors:['Black','Bone'],desc:'Premium fleece hoodie with a minimal RAVAN signature.',new:0,sale:0},
{id:'5',name:'Shadowline Bomber',cat:'women',price:4299,old:0,tag:'NEW',sizes:['XS','S','M','L'],colors:['Black'],desc:'Cropped bomber with a sculpted silhouette.',new:1,sale:0},
{id:'6',name:'Midnight Slip Dress',cat:'women',price:3599,old:4299,tag:'SALE',sizes:['XS','S','M','L'],colors:['Black'],desc:'Fluid satin-inspired dress with an evening-ready profile.',new:0,sale:1},
{id:'7',name:'RAVAN 777 Cap',cat:'accessories',price:999,old:0,tag:'NEW',sizes:['OS'],colors:['Black','Grey'],desc:'Six-panel cap finished with a subtle 777 mark.',new:1,sale:0},
{id:'8',name:'Ravan Chain',cat:'accessories',price:1299,old:0,tag:'',sizes:['OS'],colors:['Silver'],desc:'Minimal statement chain designed for everyday layering.',new:0,sale:0},
{id:'9',name:'Void Long Sleeve',cat:'women',price:2199,old:0,tag:'',sizes:['XS','S','M','L'],colors:['Black'],desc:'Second-skin long sleeve with soft stretch.',new:0,sale:0},
{id:'10',name:'Monolith Sneaker',cat:'unisex',price:5499,old:0,tag:'NEW',sizes:['6','7','8','9','10'],colors:['Black','White'],desc:'Minimal low-top sneaker with a bold sole.',new:1,sale:0},
{id:'11',name:'Afterdark Mini Bag',cat:'accessories',price:2399,old:2999,tag:'SALE',sizes:['OS'],colors:['Black'],desc:'Compact crossbody bag with adjustable strap.',new:0,sale:1},
{id:'12',name:'Power Tailored Blazer',cat:'women',price:5799,old:0,tag:'NEW',sizes:['XS','S','M','L'],colors:['Black'],desc:'Sharp tailored blazer with an architectural silhouette.',new:1,sale:0}];
let filter='all',cart=JSON.parse(localStorage.ravanCart||'[]'),wish=JSON.parse(localStorage.ravanWish||'[]'),cur,selSize,selColor;
const money=n=>'₹'+n.toLocaleString('en-IN');
function save(){localStorage.ravanCart=JSON.stringify(cart);localStorage.ravanWish=JSON.stringify(wish);document.getElementById('cc').textContent=cart.reduce((a,x)=>a+x.qty,0);document.getElementById('wc').textContent=wish.length}
function setFilter(f){filter=f;document.querySelectorAll('.chips button').forEach(b=>b.classList.toggle('active',b.dataset.f==f));render();document.getElementById('shop').scrollIntoView({behavior:'smooth'});closeM()}
function card(p){return `<article class="card" onclick="openProduct('${p.id}')"><div class="pic"><img src="assets/${p.id}.svg" alt="${p.name}">${p.tag?`<span class="badge">${p.tag}</span>`:''}<button class="heart ${wish.includes(p.id)?'saved':''}" onclick="event.stopPropagation();toggleWish('${p.id}')">${wish.includes(p.id)?'♥':'♡'}</button></div><div class="info"><div><h3>${p.name}</h3><p>${p.cat.toUpperCase()}</p></div><div class="price">${p.old?`<span class="old">${money(p.old)}</span>`:''}${money(p.price)}</div></div></article>`}
function render(){let q=(document.getElementById('q')?.value||'').toLowerCase();let a=products.filter(p=>(filter==='all'||p.cat===filter||(filter==='new'&&p.new)||(filter==='sale'&&p.sale)||(filter==='men'&&p.cat==='unisex')||(filter==='women'&&p.cat==='unisex'))&&(p.name+p.desc).toLowerCase().includes(q));let s=document.getElementById('sort')?.value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);if(s==='newest')a.sort((x,y)=>y.new-x.new);document.getElementById('grid').innerHTML=a.map(card).join('')||'<p>No products found.</p>';if(document.getElementById('search').classList.contains('open'))document.getElementById('results').innerHTML='<div class="grid">'+a.map(card).join('')+'</div>'}
function openProduct(id){cur=products.find(p=>p.id===id);selSize=cur.sizes[0];selColor=cur.colors[0];document.getElementById('detail').innerHTML=`<div class="detail"><div class="detailimg"><img src="assets/${cur.id}.svg" alt="${cur.name}"></div><div class="copy"><small>${cur.cat.toUpperCase()} / RAVAN</small><h2>${cur.name}</h2><div>${cur.old?`<span class="old">${money(cur.old)}</span>`:''}${money(cur.price)}</div><p>${cur.desc}</p><small>SIZE</small><div class="opts" id="sizes">${cur.sizes.map(x=>`<button class="${x==selSize?'sel':''}" onclick="pickSize('${x}')">${x}</button>`).join('')}</div><small>COLOUR</small><div class="opts" id="colors">${cur.colors.map(x=>`<button class="${x==selColor?'sel':''}" onclick="pickColor('${x}')">${x}</button>`).join('')}</div><button class="btn full" onclick="add()">ADD TO BAG — ${money(cur.price)}</button></div></div>`;document.getElementById('modal').classList.add('open')}
function pickSize(x){selSize=x;document.querySelectorAll('#sizes button').forEach(b=>b.classList.toggle('sel',b.textContent===x))}
function pickColor(x){selColor=x;document.querySelectorAll('#colors button').forEach(b=>b.classList.toggle('sel',b.textContent===x))}
function add(){let x=cart.find(x=>x.id===cur.id&&x.size===selSize&&x.color===selColor);x?x.qty++:cart.push({id:cur.id,size:selSize,color:selColor,qty:1});save();closeM();openCart()}
function toggleWish(id){let i=wish.indexOf(id);i<0?wish.push(id):wish.splice(i,1);save();render()}
function openCart(){let h='',t=0;cart.forEach((x,i)=>{let p=products.find(p=>p.id===x.id);t+=p.price*x.qty;h+=`<div class="row"><img src="assets/${p.id}.svg"><div><h4>${p.name}</h4><p>${x.size} / ${x.color}</p><div class="qty"><button onclick="qty(${i},-1)">−</button> ${x.qty} <button onclick="qty(${i},1)">+</button></div></div><div>${money(p.price*x.qty)}<br><button class="remove" onclick="del(${i})">REMOVE</button></div></div>`});document.getElementById('cartItems').innerHTML=h||'<p>No items in your bag.</p>';document.getElementById('total').textContent=money(t);document.getElementById('cart').classList.add('open')}
function qty(i,d){cart[i].qty=Math.max(1,cart[i].qty+d);save();openCart()}function del(i){cart.splice(i,1);save();openCart()}
function openWish(){document.getElementById('wishItems').innerHTML=wish.map(id=>{let p=products.find(p=>p.id===id);return `<div class="row"><img src="assets/${p.id}.svg"><div><h4>${p.name}</h4><p>${money(p.price)}</p></div><button class="remove" onclick="toggleWish('${id}');openWish()">REMOVE</button></div>`}).join('')||'<p>No saved products.</p>';document.getElementById('wish').classList.add('open')}
function openSearch(){document.getElementById('search').classList.add('open');document.getElementById('q').focus();render()}
function openFilters(){document.getElementById('filters').classList.add('open')}
function closeM(){document.querySelectorAll('.overlay').forEach(x=>x.classList.remove('open'))}
document.getElementById('chips').innerHTML=['all','men','women','accessories','new','sale'].map(x=>`<button data-f="${x}" onclick="setFilter('${x}')">${x==='all'?'All':x.replace(/^./,c=>c.toUpperCase())}</button>`).join('');
document.querySelector('#chips button').classList.add('active');save();render();