ALTER TABLE products ADD COLUMN brand TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN seller TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN image_url TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN product_url TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN affiliate_url TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN stock INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN featured INTEGER DEFAULT 0;
